SUCCESS = 0
VALIDATION_ERROR = 1000
UNAUTHORIZED = 1001
FORBIDDEN = 1002
NOT_FOUND = 1003
CONFLICT = 1004
INTERNAL_ERROR = 1500

ERROR_MESSAGES = {
    SUCCESS: "success",
    VALIDATION_ERROR: "validation_error",
    UNAUTHORIZED: "unauthorized",
    FORBIDDEN: "forbidden",
    NOT_FOUND: "not_found",
    CONFLICT: "conflict",
    INTERNAL_ERROR: "internal_error",
}

# Chat工作台：服务端权限、互斥和执行就绪错误。
CHAT_SPACE_FORBIDDEN = 2501
CHAT_NOT_FOUND = 2502
CHAT_REPOSITORY_UNAVAILABLE = 2503
CHAT_CONFLICT = 2504
CHAT_EXECUTION_NOT_READY = 2505
CHAT_STATE_UNKNOWN = 2506
CHAT_CLEANUP_UNVERIFIED = 2507

CHAT_RESOURCE_LIMIT = 2508
CHAT_CONTEXT_UNAVAILABLE = 2509

# Project governance: distinct from general Chat execution errors.
GOVERNANCE_FORBIDDEN = 2601
GOVERNANCE_BINDING_UNAVAILABLE = 2602
GOVERNANCE_SNAPSHOT_UNAVAILABLE = 2603
GOVERNANCE_RESULT_INVALID = 2604
GOVERNANCE_WRITER_UNAVAILABLE = 2605
GOVERNANCE_VERSION_CONFLICT = 2606
