export const cssVariables = {
  background: "--mb-background",
  sidebar: "--ops-sidebar",
  panel: "--mb-panel",
  panelRaised: "--ops-panel-raised",
  input: "--ops-input",
  border: "--mb-border",
  borderSoft: "--ops-border-soft",
  accent: "--mb-accent",
  accentHover: "--ops-accent-hover",
  accentMuted: "--mb-accent-muted",
  text: "--mb-text",
  heading: "--mb-heading",
  muted: "--mb-muted",
  quiet: "--ops-quiet",
  success: "--ops-success",
  warning: "--ops-warning",
  danger: "--ops-danger",
  info: "--ops-info",
} as const;
